- menu_name: "Servizi"

- name: "Contatti"
  url: "/contact/"
  title: "Contatti"

- name: "RSS"
  url: "/feed.xml"
  title: "Abbonati a feed RSS"

- name: "Atom"
  url: "/atom.xml"
  title: "Abbonati ad Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Mappa sito per Google Webmaster Tools"
