- menu_name: "Servizi"

- name: "Contatti"
  url: "/centenario/contact/"
  title: "Contatti"

- name: "RSS"
  url: "/centenario/feed.xml"
  title: "Abbonati a feed RSS"

- name: "Atom"
  url: "/centenario/atom.xml"
  title: "Abbonati ad Atom Feed"

- name: "sitemap.xml"
  url: "/centenario/sitemap.xml"
  title: "Mappa sito per Google Webmaster Tools"
